import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Datamodules extends StatelessWidget {
  List listeMetiers = [
    "Platrier",
    "Plombier",
    "Charpentier",
    "Cordonnier",
    "Tailleur",
    "Graveur",
    "Bricoleur",
    "Menuisier",
    "Papierier",
    "Carrossier",
    "Serrurerie",
    "Plomberie",
    "Metallier",
    "Gypse",
    "Fonderie",
    "Ennoblissement",
    "Décorateur",
    "Coiffure",
    "Journaliste",
    "Photographe",
    "Graphiste",
    "Peintre"
  ];

  List listeCategories = [
    'Jardinage',
    'Maçonnerie',
    'Electricité et électronique',
    'Électroménager',
    'Textile, vêtement & chaussures',
    'Aide à la maison',
    'Location de véhicule',
    'Restauration rapide',
    'Transports en commun',
    'Services aux clients',
    'Hôtellerie / Tourisme',
    'Entretien corporels',
    'Nettoyage professionnel',
    'Construction mécanique/automobile',
    'Autres services industriels',
    'Menuiserie',
    'Couture',
    'Papeterie',
    'Impression technique',
    'Design graphique',
    'Jeux vidéo & consoles',
    'Livraison de produits alimentaires',
    'Emballages divers',
    'Matériel agricole',
    'Fabrication machines & outillage',
    'Fournitures pour baignade',
    'Santé & bien-être',
    'Education & formation',
    'Assurances',
    'Diversification financière',
    'Diverses activités',
    'Bricolage',
    'Magasin spécialisés',
    'Evénementiels',
    'Informatique',
    'Photographies',
    'Audiovisuel',
    'Conseil juridique',
    'Publicité & communication',
    'Réseaux sociaux marketing'
  ];
  List<Map<String, dynamic>> listProfessionnel = [
    {
      "IdProfessionnel": 1,
      "Nom": "KAMILI",
      "Prenom": "Rachid",
      "Surnom": "Slawi",
      "Sexe": "M",
      "Photo": "/assets/Images/avatar.jpg",
      "Email": "rachidkamili@gmail.com",
      "Telephone1": "06-11-22-33-44",
      "Telephone2": "",
      "Adresse": "Salé",
      "Description": "Pour tous vos travaux de peiture, veuillez me contacter",
      "Ville": "Salé",
      "Metier": "Peintre",
      "Categorie": "Bâtiment",
      "NbrePoints": 5,
    },
    {
      "IdProfessionnel": 2,
      "Nom": "KHALDI",
      "Prenom": "El Ouafi",
      "Surnom": "",
      "Sexe": "M",
      "Photo": "/assets/Images/bureau.jpg",
      "Email": "khaldielouafi@gmail.com",
      "Telephone1": "06-22-33-44-55",
      "Telephone2": "",
      "Adresse": "Fès",
      "Description": "Des Coifes à la demande avec des prix imbatables",
      "Ville": "Fès",
      "Metier": "Coiffeur",
      "Categorie": "Esthétique",
      "NbrePoints": 3,
    },
    {
      "IdProfessionnel": 3,
      "Nom": "RAHALI",
      "Prenom": "Salma",
      "Surnom": "Coiffeura",
      "Sexe": "F",
      "Photo": "/assets/Images/artifices.jpg",
      "Email": "rahalisalma@gmail.com",
      "Telephone1": "06-33-44-55-66",
      "Telephone2": "",
      "Adresse": "Hay Riad",
      "Description": "Nous avons les meilleurs coupes",
      "Ville": "Rabat",
      "Metier": "Coiffeur",
      "Categorie": "Esthétique",
      "NbrePoints": 2,
    },
  ];

  Map<String, List<String>> listeRegions = {
    "L'Oriental": [
      'Oujda',
      'Nador',
      'Driouch',
      'Jerada',
      'Berkan',
      'Taourirt',
      'Guercif',
      'Figuig',
    ],
    "Marrakech-Safi": [
      'Marrakech',
      'Chichaoua',
      'Al Haouz',
      'Kelâa des Sraghna',
      'Essaouira',
      'Rehamna',
      'Safi',
      'Youssoufia'
    ],
    "Draa-Tafilalet": [
      'Errachidia',
      'Ouarzazate',
      'Midelt',
      'Tinghir',
      'Zagora'
    ],
    "Fès-Meknès": [
      'Fès',
      'Meknès',
      'El Hajeb',
      'Ifrane',
      'Moulay Yacoub',
      'Sefrou',
      'Boulemane',
      'Taounate',
      'Taza'
    ],
    "Guelmim-Oued-Noun": [
      'Guelmim',
      'Assa-Zag',
      'Tan-Tan',
      'Sidi Ifni',
    ],
    "Tanger-Tétouan-Al Hoceima": [
      "Tanger-Assilah",
      "M'diq-Fnideq",
      "Tétouan",
      "Fahs-Anjra",
      "Larache",
      "Al Hoceima",
      "Chefchaouen",
      "Ouazzane",
    ],
    "Souss-Massa": [
      'Agadir Ida-Ou-Tanane',
      'Inezgane-Aït Melloul',
      'Chtouka-Aït Baha',
      'Taroudannt',
      'Tiznit',
      'Tata',
    ],
    "Casablanca-Settat": [
      'Casablanca',
      'Mohammadia',
      'El Jadida',
      'Nouaceur',
      'Médiouna',
      'Benslimane',
      'Berrechid',
      'Settat',
      'Sidi Bennour'
    ],
    "Dakhla-Oued Eddahab": ['Oued Ed-Dahab', 'Aousserd'],
    'Béni Mellal-Khénifra': [
      'Béni Mellal',
      'Azilal',
      'Fquih Ben Salah',
      'Khénifra',
      'Khouribga'
    ],
    "Rabat-Salé-Kénitra": [
      'Rabat',
      'Salé',
      'Skhirate-Témara',
      'Kénitra',
      'Khémisset',
      'Sidi Kacem',
      'Sidi Slimane'
    ],
    "Laâyoune-Sakia Al Hamra": [
      'Laâyoune',
      'Boujdour',
      'Tarfaya',
      'Es-Semara',
    ],
  };

  Datamodules({super.key});

  @override
  Widget build(BuildContext context) {
    return const Placeholder();
  }
}
